In [3]:
import numpy as np
from numpy import linalg as la
from numpy import mat

In [4]:
A = mat([[1,2,3],[4,5,6]])

In [6]:
U,sigma,VT = la.svd(A)

In [7]:
U

matrix([[-0.3863177 , -0.92236578],
        [-0.92236578,  0.3863177 ]])

In [8]:
sigma

array([ 9.508032  ,  0.77286964])

In [9]:
VT

matrix([[-0.42866713, -0.56630692, -0.7039467 ],
        [ 0.80596391,  0.11238241, -0.58119908],
        [ 0.40824829, -0.81649658,  0.40824829]])

In [10]:
B = mat([[-0.44,-0.3,0.57,0.58,0.25],[-0.13,-0.33,-0.59,0,0.73],[-0.48,-0.51,-0.37,0,-0.61],
        [-0.70,0.35,0.15,-0.58,0.16],[-0.26,0.65,-0.41,0.58,-0.09]])

In [11]:
B

matrix([[-0.44, -0.3 ,  0.57,  0.58,  0.25],
        [-0.13, -0.33, -0.59,  0.  ,  0.73],
        [-0.48, -0.51, -0.37,  0.  , -0.61],
        [-0.7 ,  0.35,  0.15, -0.58,  0.16],
        [-0.26,  0.65, -0.41,  0.58, -0.09]])

In [12]:
U,sigma,VT = la.svd(B)

In [13]:
sigma

array([ 1.00645824,  1.00572336,  1.00065199,  0.99882106,  0.99499467])

In [19]:
C = mat([[1,0,1,0,0],[0,1,0,0,0],[1,1,0,0,0],[1,0,0,1,1],[0,0,0,1,0]])

In [20]:
U_C,sigma_C,VT_C = la.svd(C)

In [21]:
sigma_C

array([ 2.15066649,  1.50487451,  1.22088407,  0.69874897,  0.36218548])

In [22]:
U_C

matrix([[-0.45536179,  0.21336928, -0.76496969, -0.35231975, -0.19445141],
        [-0.13594788,  0.45022881,  0.49418646, -0.2442713 , -0.68914692],
        [-0.49286086,  0.56938065,  0.24242708,  0.12500581,  0.59874578],
        [-0.70263065, -0.51291304,  0.14728067,  0.40761354, -0.23535076],
        [-0.19380956, -0.40557794,  0.30023096, -0.79650931,  0.270885  ]])

In [23]:
VT_C

matrix([[-0.7676008 , -0.29237855, -0.21173055, -0.41681973, -0.32670368],
        [ 0.17930856,  0.67753786,  0.14178543, -0.6103439 , -0.34083443],
        [-0.30736902,  0.60334438, -0.62657029,  0.3665472 ,  0.12063445],
        [ 0.25803199, -0.17068432, -0.50421506, -0.55656006,  0.58334761],
        [ 0.46645604, -0.24959901, -0.53688351,  0.09811061, -0.64980728]])

In [24]:
D = mat([[1,0,1,1,0],[0,1,1,0,0],[1,0,0,0,0],[0,0,0,1,1],[0,0,0,1,0]])

In [25]:
U_D,sigma_D,VT_D = la.svd(D)

In [26]:
U_D

matrix([[-0.7676008 ,  0.17930856, -0.30736902, -0.25803199, -0.46645604],
        [-0.29237855,  0.67753786,  0.60334438,  0.17068432,  0.24959901],
        [-0.21173055,  0.14178543, -0.62657029,  0.50421506,  0.53688351],
        [-0.41681973, -0.6103439 ,  0.3665472 ,  0.55656006, -0.09811061],
        [-0.32670368, -0.34083443,  0.12063445, -0.58334761,  0.64980728]])

In [27]:
VT_D

matrix([[-0.45536179, -0.13594788, -0.49286086, -0.70263065, -0.19380956],
        [ 0.21336928,  0.45022881,  0.56938065, -0.51291304, -0.40557794],
        [-0.76496969,  0.49418646,  0.24242708,  0.14728067,  0.30023096],
        [ 0.35231975,  0.2442713 , -0.12500581, -0.40761354,  0.79650931],
        [ 0.19445141,  0.68914692, -0.59874578,  0.23535076, -0.270885  ]])

In [28]:
sigma_D

array([ 2.15066649,  1.50487451,  1.22088407,  0.69874897,  0.36218548])